name: Get BilBil Live m3u8
on:
  schedule:
    - cron: '0 0/2 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

############################################bilbil##############################################################
#蠟筆小新1
    - name: Get Crayon_Shinchan1.m3u8
      run: |
        touch ./Crayon_Shinchan1.m3u8
        sudo cat >./Crayon_Shinchan1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000
        $(python3 ./bilibili.py 26329057)
        EOL
#蠟筆小新2
    - name: Get Crayon_Shinchan2.m3u8
      run: |
        touch ./Crayon_Shinchan2.m3u8
        sudo cat >./Crayon_Shinchan2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000
        $(python3 ./bilibili.py 10375360)
        EOL
#蠟筆小新3
    - name: Get Crayon_Shinchan3.m3u8
      run: |
        touch ./Crayon_Shinchan3.m3u8
        sudo cat >./Crayon_Shinchan3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000
        $(python3 ./bilibili.py 26706595)
        EOL
#蠟筆小新4
    - name: Get Crayon_Shinchan4.m3u8
      run: |
        touch ./Crayon_Shinchan4.m3u8
        sudo cat >./Crayon_Shinchan4.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000
        $(python3 ./bilibili.py 27178028)
        EOL
#名偵探柯南
    - name: Get Conan.m3u8
      run: |
        touch ./Conan.m3u8
        sudo cat >./Conan.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000
        $(python3 ./bilibili.py 181453)
        EOL
#小新多拉A夢小丸子柯南
    - name: Get more_TV_24.m3u8
      run: |
        touch ./more_TV_24.m3u8
        sudo cat >./more_TV_24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000
        $(python3 ./bilibili.py 21557299)
        EOL
#多拉A夢1
    - name: Get Doraemon1.m3u8
      run: |
        touch ./Doraemon1.m3u8
        sudo cat >./Doraemon1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000
        $(python3 ./bilibili.py 14745943)
        EOL
#多拉A夢2
    - name: Get Doraemon2.m3u8
      run: |
        touch ./Doraemon2.m3u8
        sudo cat >./Doraemon2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000
        $(python3 ./bilibili.py 27383329)
        EOL
#多拉A夢3
    - name: Get Doraemon3.m3u8
      run: |
        touch ./Doraemon3.m3u8
        sudo cat >./Doraemon3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000
        $(python3 ./bilibili.py 27311355)
        EOL




############################################################################################################
    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
