name: Get douyu Live m3u8
on:
  schedule:
    - cron: '0 0/2 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
    - name: Install PyExecJS
      run: |
        pip install PyExecJS
############################################huya虎牙##############################################################
#海蓮寶寶1
    - name: Get huya_spongebob1.m3u8
      run: |
        touch ./huya_spongebob1.m3u8
        sudo cat >./huya_spongebob1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(python3 ./huya.py 20301656)
        EOL
#海蓮寶寶1
    - name: Get huya_spongebob2.m3u8
      run: |
        touch ./huya_spongebob2.m3u8
        sudo cat >./huya_spongebob2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(python3 ./huya.py 19552901)
        EOL











############################################################################################################
    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
